In [1]:

import numpy as np
from numpy import genfromtxt


In [2]:
#
#url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#https://archive.ics.uci.edu/dataset/53/iris
#

In [3]:
file_path = "../data/iris.data"
#data = np.genfromtxt(file_path, delimiter=',', dtype=None, encoding='utf-8')
data = np.genfromtxt(file_path, delimiter=',', dtype=str, encoding='utf-8')


In [4]:
data[:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype='<U15')

In [5]:
print(data.shape)
print(data[0])

(150, 5)
['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']


In [6]:
target = data[:, 4]
target[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [7]:
features = data[:, :4].astype(float)
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [8]:
features = np.delete(data, 4, axis=1)
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [9]:
print(data.shape)

(150, 5)


In [10]:
data_numeric = data[:, :-1].astype(float)
data_numeric[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

3. Порахувати mean, median, standard deviation для 1-ї колонки


In [11]:
col1 = data_numeric[:, 0]
col1_mean = np.mean(col1)
col1_median = np.median(col1)
col1_std = np.std(col1)
print(col1_mean, col1_median, col1_std)

5.843333333333334 5.8 0.8253012917851409


4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [12]:
num_nans = 20
total_elements = data_numeric.size
flat_indices = np.random.choice(total_elements, size=num_nans, replace=False)
flat_indices

array([ 94,  57, 189, 563,   5,  14, 578,  18, 485, 398, 544, 257, 443,
       239, 258, 404, 283, 400,  73,  81], dtype=int32)

In [13]:
#num_rows, num_cols = data.shape
#rng = np.random.default_rng()
#flat_indices = rng.choice(num_rows * num_cols, size=20, replace=False)
print(flat_indices)
data_numeric.ravel()[flat_indices] = np.nan

[ 94  57 189 563   5  14 578  18 485 398 544 257 443 239 258 404 283 400
  73  81]


In [14]:
col1

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, nan, nan, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, nan, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [15]:
print("count of np.nan:", np.sum(np.isnan(data_numeric)))

count of np.nan: 20


5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [16]:
col1 = data_numeric[:, 0]
nan_positions_first_col = np.where(np.isnan(col1))[0]
nan_positions_first_col


array([100, 101, 136])

6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [17]:
mask = (data_numeric[:, 2] > 1.5) & (data_numeric[:, 0] < 5.0)
filtered_data = data_numeric[mask]
filtered_data

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [18]:
print("Filtered raws:", filtered_data.shape[0])

Filtered raws: 6


  7. Замінити всі значення np.nan на 0

In [19]:
data = np.nan_to_num(data_numeric, nan=0.0)
print("count of np.nan:", np.sum(np.isnan(data)))

count of np.nan: 0


8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [20]:
unique_vals, counts = np.unique(data_numeric, return_counts=True)

In [21]:
print("Unique and count:")
for val, cnt in zip(unique_vals, counts):
    print(f"{val:.1f}: {cnt}")

Unique and count:
0.1: 6
0.2: 28
0.3: 7
0.4: 7
0.5: 1
0.6: 1
1.0: 8
1.1: 4
1.2: 7
1.3: 20
1.4: 18
1.5: 25
1.6: 11
1.7: 5
1.8: 11
1.9: 7
2.0: 6
2.1: 6
2.2: 6
2.3: 12
2.4: 5
2.5: 11
2.6: 5
2.7: 9
2.8: 13
2.9: 9
3.0: 26
3.1: 12
3.2: 12
3.3: 8
3.4: 11
3.5: 8
3.6: 3
3.7: 4
3.8: 6
3.9: 5
4.0: 5
4.1: 3
4.2: 5
4.3: 3
4.4: 8
4.5: 9
4.6: 7
4.7: 7
4.8: 9
4.9: 11
5.0: 14
5.1: 17
5.2: 6
5.3: 3
5.4: 8
5.5: 10
5.6: 12
5.7: 10
5.8: 9
5.9: 5
6.0: 8
6.1: 9
6.2: 4
6.3: 8
6.4: 8
6.5: 5
6.6: 3
6.7: 10
6.8: 3
6.9: 5
7.0: 1
7.1: 1
7.2: 3
7.3: 1
7.4: 1
7.6: 1
7.7: 4
7.9: 1
nan: 20


In [22]:
counts

array([ 6, 28,  7,  7,  1,  1,  8,  4,  7, 20, 18, 25, 11,  5, 11,  7,  6,
        6,  6, 12,  5, 11,  5,  9, 13,  9, 26, 12, 12,  8, 11,  8,  3,  4,
        6,  5,  5,  3,  5,  3,  8,  9,  7,  7,  9, 11, 14, 17,  6,  3,  8,
       10, 12, 10,  9,  5,  8,  9,  4,  8,  8,  5,  3, 10,  3,  5,  1,  1,
        3,  1,  1,  1,  4,  1, 20])

9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [23]:
n_rows = data.shape[0]
split_idx = n_rows // 2
part1 = data[:split_idx, :]      # first 75 rows
part2 = data[split_idx:, :]      # last 75 rows, 4 columns
print("part1 shape:", part1.shape, "part2 shape:", part2.shape)

part1 shape: (75, 4) part2 shape: (75, 4)


10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [24]:
part1_sorted = part1[part1[:, 0].argsort()]
part2_sorted = part2[(-part2[:, 0]).argsort()]


In [25]:
print("part1", part1_sorted)

part1 [[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 0.  0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 0.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 0.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.5 1.6 0.6]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  3.6 0.  0.2]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.3 0.  0.5]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 0. ]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 0.  1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 4.2 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 3.5 1.3 0.2]
 [5.6 0.  0.  1.3]
 [5.6 

In [26]:
print("part2:", part2_sorted)

part2: [[7.9 3.8 6.4 2. ]
 [7.7 2.8 6.7 2. ]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [7.7 3.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [7.4 2.8 6.1 1.9]
 [7.3 2.9 6.3 1.8]
 [7.2 3.6 6.1 2.5]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.9 3.1 5.4 2.1]
 [6.9 3.1 5.1 2.3]
 [6.8 3.  5.5 2.1]
 [6.8 2.8 4.8 1.4]
 [6.8 3.2 5.9 2.3]
 [6.7 3.1 4.7 1.5]
 [6.7 3.  5.2 2.3]
 [6.7 3.1 5.6 0. ]
 [6.7 3.3 5.7 2.1]
 [6.7 2.5 5.8 1.8]
 [6.7 3.  5.  1.7]
 [6.7 3.3 0.  2.5]
 [6.6 3.  4.4 1.4]
 [6.5 3.2 5.1 0. ]
 [6.5 3.  5.2 2. ]
 [6.5 3.  5.8 2.2]
 [6.5 3.  5.5 1.8]
 [6.4 3.1 5.5 1.8]
 [6.4 2.8 5.6 2.2]
 [6.4 2.7 5.3 1.9]
 [6.4 2.8 5.6 2.1]
 [6.4 3.2 5.3 2.3]
 [6.3 2.5 5.  1.9]
 [6.3 2.9 5.6 1.8]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [6.3 2.3 4.4 1.3]
 [6.2 2.9 4.3 1.3]
 [6.2 2.8 4.8 1.8]
 [6.2 3.4 5.4 2.3]
 [6.1 3.  4.9 1.8]
 [6.1 3.  4.6 1.4]
 [6.1 2.6 5.6 1.4]
 [6.  2.9 4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.  3.  4.8 1.8]
 [6.  2.2 5.  1.5]
 [6.  2.7 5.1 1.6]
 [5.9 3.  5.1 1.8]
 [5.8

11. Зібрати обидва массиви в одне ціле

In [27]:
combined = np.vstack((part1_sorted, part2_sorted))
print("United shape:", combined.shape)
print(combined)



United shape: (150, 4)
[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.1 0.  0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 0.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 0.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.5 1.6 0.6]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [5.  3.6 0.  0.2]
 [5.  2.  3.5 1. ]
 [5.  3.2 1.2 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.8 1.5 0.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.1 3.3 0.  0.5]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [5.2 2.7 3.9 0. ]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.4 0.  1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 4.2 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.5 3.5 1.3 0.2]
 [5.6 0.

12. Знайти найбільш часто повторюване значення в массиві

In [28]:
unique_vals, counts = np.unique(data, return_counts=True)
print("unique_vals:", unique_vals)
print("counts:", counts)
most_frequent = unique_vals[np.argmax(counts)]
print("Most frequent values:", most_frequent)

unique_vals: [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
counts: [20  6 28  7  7  1  1  8  4  7 20 18 25 11  5 11  7  6  6  6 12  5 11  5
  9 13  9 26 12 12  8 11  8  3  4  6  5  5  3  5  3  8  9  7  7  9 11 14
 17  6  3  8 10 12 10  9  5  8  9  4  8  8  5  3 10  3  5  1  1  3  1  1
  1  4  1]
Most frequent values: 0.2


13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [29]:
def transform_column(col):
    mean_val = np.mean(col)
    return np.where(col < mean_val, col * 2, col / 4)


14. Застосувати отриману функцію до 3-ї колонки

In [30]:
combined[:, 2] = transform_column(combined[:, 2])
print(combined)

[[4.3   3.    2.2   0.1  ]
 [4.4   2.9   2.8   0.2  ]
 [4.4   3.2   2.6   0.2  ]
 [4.4   3.    2.6   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.6   2.    0.2  ]
 [4.6   3.1   0.    0.2  ]
 [4.6   3.4   2.8   0.3  ]
 [4.6   0.    2.8   0.2  ]
 [4.7   3.2   2.6   0.2  ]
 [4.7   3.2   3.2   0.2  ]
 [4.8   3.    2.8   0.3  ]
 [4.8   3.1   3.2   0.2  ]
 [4.8   3.4   3.8   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.    2.8   0.1  ]
 [4.9   2.4   6.6   1.   ]
 [4.9   3.1   3.    0.1  ]
 [4.9   3.1   3.    0.1  ]
 [4.9   0.    2.8   0.2  ]
 [4.9   3.1   3.    0.1  ]
 [5.    3.3   2.8   0.2  ]
 [5.    3.5   2.6   0.3  ]
 [5.    3.5   3.2   0.6  ]
 [5.    3.4   3.2   0.4  ]
 [5.    3.4   3.    0.2  ]
 [5.    3.6   0.    0.2  ]
 [5.    2.    7.    1.   ]
 [5.    3.2   2.4   0.2  ]
 [5.    3.    3.2   0.2  ]
 [5.1   3.7   3.    0.4  ]
 [5.1   3.8   3.    0.3  ]
 [5.1   3.5   2.8   0.3  ]
 [5.1   3.8   3.2   0.2  ]
 [5.1   3.3   0.    0.5  ]
 [5.1   3.5   2.8   0.2  ]
 [5.1   3.8   3.8   0.4  ]
 